scoreboard objectives add death_timer dummy 
scoreboard objectives add loop1 dummy 
scoreboard objectives add remain_people dummy
scoreboard objectives add max_people dummy
scoreboard objectives add death dummy
scoreboard objectives add cooldown dummy
scoreboard objectives add has_weapons dummy
scoreboard objectives add arg1 dummy
scoreboard objectives add arg2 dummy
scoreboard objectives add arg3 dummy